In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv(
    r"C:/Users/abc/Desktop/data/Finance/finance1.csv",
    encoding='latin1'
)
df.head()

,Project Code,Title,Commitment in U.A,Country,Starting Date,Status,Source of Financing,Sector,Sovereign
0,P-MG-H00-002,Madagascar - Industrialisation and Financial S...,"12,080,000.00",Madagascar,28 Oct 2020,Approved,African Development Fund,Finance,Sovereign
1,P-Z1-H00-063,Multinational - Domestic debt markets developm...,"1,500,000.00",Multinational,13 Oct 2020,Implementation,Fragile States Facility,Finance,Sovereign
2,P-MG-HAZ-001,Madagascar - SME Business Linkages Program,"1,000,000.00",Madagascar,15 May 2020,Implementation,Fragile States Facility,Finance,Sovereign
3,P-MU-H00-004,Mauritius - Stock Exchange Mauritius (SEM) Pro...,"430,000.00",Mauritius,27 Apr 2020,Implementation,Middle Income Countries Fund,Finance,Sovereign
4,P-AO-HAB-009,Angola - Line of Credit to « Banco Millennium ...,"23,415,605.04",Angola,15 Apr 2020,Approved,African Development Bank,Finance,Non Sovereign

In [2]:
df.describe()

,Project Code,Title,Commitment in U.A,Country,Starting Date,Status,Source of Financing,Sector,Sovereign
count,337,336,336,336,336,336,336,336,281
unique,337,320,305,47,262,4,9,1,3
top,P-MG-H00-002,Multinational - COMESA Regional Trade and Proj...,"70,832,064.26",Multinational,17 Jul 2019,Completion,African Development Bank,Finance,Sovereign
freq,1,3,4,65,7,210,224,336,167

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 355 entries, 0 to 354
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Project Code         337 non-null    str
 1   Title                336 non-null    str
 2   Commitment in U.A    336 non-null    str
 3   Country              336 non-null    str
 4   Starting Date        336 non-null    str
 5   Status               336 non-null    str
 6   Source of Financing  336 non-null    str
 7   Sector               336 non-null    str
 8   Sovereign            281 non-null    str
dtypes: str(9)
memory usage: 25.1 KB

In [4]:
df['Status'].unique()

<StringArray>
['Approved', 'Implementation', nan, 'Completion', 'Cancelled']
Length: 5, dtype: str

In [5]:
df['Source of Financing'].unique()

<StringArray>
[                          'African Development Fund',
                            'Fragile States Facility',
                       'Middle Income Countries Fund',
                           'African Development Bank',
         'Fund for African Private Sector Assistance',
                                                  nan,
 'Multi donor Trust Fund for Countries in Transition',
                             'Global Affairs Canada ',
  'NEPAD Infrastructure Project Preparation Facility',
                                'Nigerian Trust Fund']
Length: 10, dtype: str

In [6]:

# 1. Remove leading/trailing spaces from column names
df.columns = df.columns.str.strip()

# 2. Convert column names to lowercase
df.columns = df.columns.str.lower()

# 3. Remove extra spaces from string values in all object columns
df = df.apply(lambda col: col.str.strip() if col.dtype == 'object' else col)

# Optional: replace multiple internal spaces with single space
df = df.apply(
    lambda col: col.str.replace(r'\s+', ' ', regex=True).str.strip()
    if col.dtype == 'object' else col
)

In [7]:
df.isna().any().any()

np.True_

In [8]:
df.isna().sum()

project code           18
title                  19
commitment in u.a      19
country                19
starting date          19
status                 19
source of financing    19
sector                 19
sovereign              74
dtype: int64

In [9]:
df=df.dropna(how='all')

In [10]:
df.isna().sum()

project code            0
title                   1
commitment in u.a       1
country                 1
starting date           1
status                  1
source of financing     1
sector                  1
sovereign              56
dtype: int64

In [11]:
df.head()

,project code,title,commitment in u.a,country,starting date,status,source of financing,sector,sovereign
0,P-MG-H00-002,Madagascar - Industrialisation and Financial S...,"12,080,000.00",Madagascar,28 Oct 2020,Approved,African Development Fund,Finance,Sovereign
1,P-Z1-H00-063,Multinational - Domestic debt markets developm...,"1,500,000.00",Multinational,13 Oct 2020,Implementation,Fragile States Facility,Finance,Sovereign
2,P-MG-HAZ-001,Madagascar - SME Business Linkages Program,"1,000,000.00",Madagascar,15 May 2020,Implementation,Fragile States Facility,Finance,Sovereign
3,P-MU-H00-004,Mauritius - Stock Exchange Mauritius (SEM) Pro...,"430,000.00",Mauritius,27 Apr 2020,Implementation,Middle Income Countries Fund,Finance,Sovereign
4,P-AO-HAB-009,Angola - Line of Credit to « Banco Millennium ...,"23,415,605.04",Angola,15 Apr 2020,Approved,African Development Bank,Finance,Non Sovereign

In [12]:
unique_vals = df.loc[df['source of financing'] == "Fragile States Facility", 'sovereign'].unique()

print(unique_vals)

<StringArray>
['Sovereign']
Length: 1, dtype: str

In [13]:
df['sovereign'] = df.groupby('source of financing')['sovereign'].transform(
    lambda x: x.mode().iloc[0] if not x.mode().empty else x
)
df['sovereign'].isna().sum()

np.int64(1)

In [14]:
result = df[
    (df['project code'] == 'field') &
    (df.isna().any(axis=1))
]

print(result)

Empty DataFrame
Columns: [project code, title, commitment in u.a, country, starting date, status, source of financing, sector, sovereign]
Index: []

In [15]:
nan_rows = df[df.isna().any(axis=1)]

print(nan_rows)

                       project code title commitment in u.a country  \
353  African Development Bank Group   NaN               NaN     NaN

    starting date status source of financing sector sovereign
353           NaN    NaN                 NaN    NaN       NaN

In [16]:
df = df.drop(columns=['col2'])
df = df.dropna()

KeyError: "['col2'] not found in axis"

In [ ]:
df.isna().sum()

In [ ]:
df['project code'].duplicated().any()

In [22]:
df['commitment in u.a'] = pd.to_numeric(df['commitment in u.a'])

ValueError: Unable to parse string "12,080,000.00" at position 0

In [21]:
df['commitment in u.a'].dtype()

TypeError: 'StringDtype' object is not callable

In [19]:
df.head()

,project code,title,commitment in u.a,country,starting date,status,source of financing,sector,sovereign
0,P-MG-H00-002,Madagascar - Industrialisation and Financial S...,"12,080,000.00",Madagascar,28 Oct 2020,Approved,African Development Fund,Finance,Sovereign
1,P-Z1-H00-063,Multinational - Domestic debt markets developm...,"1,500,000.00",Multinational,13 Oct 2020,Implementation,Fragile States Facility,Finance,Sovereign
2,P-MG-HAZ-001,Madagascar - SME Business Linkages Program,"1,000,000.00",Madagascar,15 May 2020,Implementation,Fragile States Facility,Finance,Sovereign
3,P-MU-H00-004,Mauritius - Stock Exchange Mauritius (SEM) Pro...,"430,000.00",Mauritius,27 Apr 2020,Implementation,Middle Income Countries Fund,Finance,Sovereign
4,P-AO-HAB-009,Angola - Line of Credit to « Banco Millennium ...,"23,415,605.04",Angola,15 Apr 2020,Approved,African Development Bank,Finance,Non Sovereign

In [23]:
df['commitment in u.a'] = df['commitment in u.a'].str.replace(",", "")
df['commitment in u.a'] = pd.to_numeric(df['commitment in u.a'])

In [24]:
df['commitment in u.a'].dtype()

TypeError: 'numpy.dtypes.Float64DType' object is not callable

In [25]:
df.info()

<class 'pandas.DataFrame'>
Index: 337 entries, 0 to 353
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   project code         337 non-null    str
 1   title                336 non-null    str
 2   commitment in u.a    336 non-null    float64
 3   country              336 non-null    str
 4   starting date        336 non-null    str
 5   status               336 non-null    str
 6   source of financing  336 non-null    str
 7   sector               336 non-null    str
 8   sovereign            336 non-null    str
dtypes: float64(1), str(8)
memory usage: 26.3 KB

In [27]:
df['starting date'] = pd.to_datetime(df['starting date'])

In [28]:
df.info()

<class 'pandas.DataFrame'>
Index: 337 entries, 0 to 353
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   project code         337 non-null    str
 1   title                336 non-null    str
 2   commitment in u.a    336 non-null    float64
 3   country              336 non-null    str
 4   starting date        336 non-null    datetime64[us]
 5   status               336 non-null    str
 6   source of financing  336 non-null    str
 7   sector               336 non-null    str
 8   sovereign            336 non-null    str
dtypes: datetime64[us](1), float64(1), str(7)
memory usage: 26.3 KB

In [29]:
df.head()

,project code,title,commitment in u.a,country,starting date,status,source of financing,sector,sovereign
0,P-MG-H00-002,Madagascar - Industrialisation and Financial S...,12080000.00,Madagascar,2020-10-28,Approved,African Development Fund,Finance,Sovereign
1,P-Z1-H00-063,Multinational - Domestic debt markets developm...,1500000.00,Multinational,2020-10-13,Implementation,Fragile States Facility,Finance,Sovereign
2,P-MG-HAZ-001,Madagascar - SME Business Linkages Program,1000000.00,Madagascar,2020-05-15,Implementation,Fragile States Facility,Finance,Sovereign
3,P-MU-H00-004,Mauritius - Stock Exchange Mauritius (SEM) Pro...,430000.00,Mauritius,2020-04-27,Implementation,Middle Income Countries Fund,Finance,Sovereign
4,P-AO-HAB-009,Angola - Line of Credit to « Banco Millennium ...,23415605.04,Angola,2020-04-15,Approved,African Development Bank,Finance,Non Sovereign

In [30]:
df["project code"].value_counts()

project code
P-MG-H00-002                      1
P-Z1-H00-063                      1
P-MG-HAZ-001                      1
P-MU-H00-004                      1
P-AO-HAB-009                      1
                                 ..
P-SL-HA0-001                      1
P-BI-H00-001                      1
P-MA-HAA-001                      1
P-MW-HA0-001                      1
African Development Bank Group    1
Name: count, Length: 337, dtype: int64

In [31]:
df = df[df["project code"] != "African Development Bank Group"]

In [32]:
df.info()

<class 'pandas.DataFrame'>
Index: 336 entries, 0 to 351
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   project code         336 non-null    str
 1   title                336 non-null    str
 2   commitment in u.a    336 non-null    float64
 3   country              336 non-null    str
 4   starting date        336 non-null    datetime64[us]
 5   status               336 non-null    str
 6   source of financing  336 non-null    str
 7   sector               336 non-null    str
 8   sovereign            336 non-null    str
dtypes: datetime64[us](1), float64(1), str(7)
memory usage: 26.2 KB